import type { Metadata } from "next";
import "./globals.css";
import { Baloo_Da_2 } from "next/font/google";
const baloo_font = Baloo_Da_2({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Daily Times 24",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={baloo_font.className}>{children}</body>
    </html>
  );
}
