import type { Metadata } from "next";
import "./globals.css";
import { Tiro_Bangla } from "next/font/google";
import Providers from "@/lib/Provider";

const tiro_Bangla = Tiro_Bangla({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Daily Times 24",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">      
      <Providers>
        <body className={tiro_Bangla.className}>{children}</body>
      </Providers>
    </html>
  );
}
